### ISSUE TITLE
App pairs on its own to another e-bike which is nearby

### ISSUE THREAD

**Issue by YarinVooDoo** [maca88/E-Bike-Edge-MultiField#7]
I think a system is needed to uniquely associate the app to your e-Bike as soon as the primary bike is read, because situations could happen in which another e-Bike is near the Garmin device and the app reads the values of this e-Bike instead.
This situation occurred just today when another Giant Trance E + joined to my ride and my Garmin was showing data from the other Giant instead of my e-MTB even if my bike was on.

The app is designed to read the data of 3 e-Bikes, if I set the data of the second and third e-Bikes to a particular value (eg 9999), can I prevent the app from associating itself with other bicycles?

**Comment by maca88** [comment]
With the latest version `0.8.0` I 've added what you suggested as the default behavior, because this is something that happen also to me :) As you already have the data field installed, you will need to update the `Secondary LEV Device Number` and `Tertiary LEV Device Number` app settings values to `-1`, which will prevent from searching for additional E-Bikes.

**Comment by YarinVooDoo** [comment]
Thank you so much! ;)
